repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=1000']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        name: prettier check
        files: \.(js|jsx|ts|tsx|json|css|scss)$
        exclude: /node_modules/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.4.0
    hooks:
      - id: eslint
        name: eslint check
        files: '\.(js|jsx|ts|tsx)$'
        exclude: '/node_modules/'

  # - repo: https://github.com/commitizen/cz-cli
  #   rev: v4.3.0
  #   hooks:
  #     - id: commitizen
  #       name: Commit Message
  #       entry: npx commitlint --edit $1
  #       language: system
  #       stages: [commit-msg]

default_install_hook_types: [pre-commit, commit-msg]
